### ISSUE TITLE
Adding new roof pieces to missing pieces

### ISSUE THREAD

**Issue by AZRacer** [OrianaVenture/Valheim-MissingPieces#13]
Hey there,

   Per our conversation in the WWE server, I am requesting a commission (real money) to add 2 new roof pieces to missing pieces. Being hard to explain but lets try the following.

2 new roof pieces, 1 grass, 1 tar, normal length and width.

They would have the same base orientation and snap points as a wood floor.
In my mind this would be copying a wood floor piece and replacing the model with a grass roof. Then adding in the attributes that make it function as a roof, water, shelter etc...

Please let me know if you would like to add this to your mod. It would seriously be a big deal for us builders.

Thanks!

**Comment by OrianaVenture** [comment]
Added in 2.1.0
