### ISSUE TITLE
Drawers make game lag a lot when trying to place

### ISSUE THREAD

**Issue by kiBe-e** [OrianaVenture/Valheim-MissingPieces#17]
While hammer is equipped and the preview of the drawer is visible fps drops significantly.

Version 2.2.0. from Thunderstore.

**Comment by OrianaVenture** [comment]
I will need to see your bepinex/logoutput.log file to help. It will show what other mods you are using and any errors the game may be throwing.

**Comment by kiBe-e** [comment]
[LogOutput.log](https://github.com/user-attachments/files/15847938/LogOutput.log)

**Comment by OrianaVenture** [comment]
I don't see any errors nor attempts to place the drawer. I am assuming you did not try to actually place one in your world. The mod works fine for me. I suspect there may be an issue with another mod that handles containers. I would start by removing those one by one and see if the problem goes away: AzuCraftyBoxes, MultiUserChest, ItemHopper, AutoFeed, Backpacks, and possibly Comfort Tweaks. Make a backup or test on a different world so you don't lose your modded items.

**Comment by kiBe-e** [comment]
https://streamable.com/uvh55g

not as laggy on solid ground apparently

ill try testing removing the mods one by one still

**Comment by kiBe-e** [comment]
Seams like its anything that can be placed down and has snapping enabled. So its not this mod. And Im too lazy to figure out what it is.
