### ISSUE TITLE
I so hope you'll update this...

### ISSUE THREAD

**Issue by Sketaful** [OrianaVenture/Valheim-MissingPieces#19]
Doesn't seem to work with the newer versions and sure hope you find time to update this. Miss the stone corners and the chests.

Also hope you're ok.

**Comment by OrianaVenture** [comment]
Missing Pieces works on the latest game version. Make sure you have updated Jotunn to 2.21.3 for game version 0.219.16. If you have other outdated piece mods it can break this one.
