### ISSUE TITLE
[Feature Request] Configurable size for Drawers

### ISSUE THREAD

**Issue by Xiaminou** [OrianaVenture/Valheim-MissingPieces#20]
It would be nice to be able to configure the size of the drawers' inventory.

**Comment by OrianaVenture** [comment]
I do not plan on adding configurations to this mod. AzuContainerSizes can do this, and WackysDatabase is able to edit everything else.

https://thunderstore.io/c/valheim/p/Azumatt/AzuContainerSizes/
https://thunderstore.io/c/valheim/p/WackyMole/WackysDatabase/
