### ISSUE TITLE
[Suggestion] smooth stone pieces like bricks

### ISSUE THREAD

**Issue by Barerock** [OrianaVenture/Valheim-MissingPieces#6]
Brick variants that use the smooth stone textures. The 1x1 is already in, but a 2x1 and slopes would be fantastic, and potentially Mistlands style arches? A stair slope would be cool as well, to make super slippery smooth ramps!

Thanks, please take your time!

**Comment by Barerock** [comment]
Ah, forgot to mention a 2x2 vertical variant, or even just retexturing the 3x2 stone brick piece would be awesome.

**Comment by Barerock** [comment]
I would also like to suggest slanted 26 degree and 45 degree glass pieces. It's bad enough that glass has 0 support, but finagling with the dividing line between each one is silly. Thanks!

**Comment by OrianaVenture** [comment]
Closing this thread, will post an update in the new issue: https://github.com/OrianaVenture/Valheim-MissingPieces/issues/14
