### ISSUE TITLE
piece_chest_wooden_drawer

### ISSUE THREAD

**Issue by UHDFreddyEST** [OrianaVenture/Valheim-MissingPieces#9]
piece_chest_wooden_drawer dosent have open and close sound like another chests hava,
if you demolish chest, then no sound

feature request: dublicate text also to open chest variation.

**Comment by OrianaVenture** [comment]
Hi UHDFreddyEST, I noticed the effects were all blank so I will be fixing that in the next update. I do not have the skills to make the text move with the opened drawer, but if I learn how to do that I will certainly add that feature to the mod.
